[build]
  # Directory containing your site. If your site is at root, this is "."
  publish = "."

  # Directory for serverless functions
  functions = "netlify/functions"

  [[redirects]]
  from = "/proposal-chat"
  to = "/proposal-chat.html"
  status = 200
  force = true
  conditions = { Role = "authenticated" }

