name: Hugging Face API Proxy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [query-ai]

jobs:
  query-ai:
    runs-on: ubuntu-latest

    steps:
    - name: Call Hugging Face API
      env:
        HF_API_KEY: ${{ secrets.HF_API_KEY }}  # Securely fetch the Hugging Face API key
        GITHUB_PAT: ${{ secrets.GH_PAT_AI }}  # Securely fetch the GitHub Personal Access Token
      run: |
        curl -X POST "https://api-inference.huggingface.co/models/tiiuae/falcon-7b-instruct" \
        -H "Authorization: Bearer $HF_API_KEY" \
        -H "Content-Type: application/json" \
        --data '{"inputs": "${{ github.event.client_payload.user_query }}", "parameters": {"max_new_tokens": 250, "temperature": 0.2, "top_p": 0.7, "repetition_penalty": 1.5}}' \
        -o response.json

    - name: Upload Response
      uses: actions/upload-artifact@v4
      with:
        name: ai-response
        path: response.json
